OnlineTicariOtomasyon/Models/Siniflar/Departman.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace OnlineTicariOtomasyon.Models.Siniflar
{
    public class Departman
    {
        [Key]
        public int DepartmanId { get; set; }

        [Column(TypeName = "Varchar"), StringLength(30)]
        public string DepartmanAd { get; set; }
        public bool Durum { get; set; }

        public ICollection<Personel> Personeller{ get; set; }
    }
}

OnlineTicariOtomasyon/Controllers/DepartmanController.cs
using OnlineTicariOtomasyon.Models.Siniflar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineTicariOtomasyon.Controllers
{
    public class DepartmanController : Controller
    {
        Context _context = new Context();
        public ActionResult Index()
        {
            var departmanlar = _context.Departmans.Where(m=>m.Durum==true).ToList();
            return View(departmanlar);
        }

        [Authorize(Roles ="A")]
        [HttpGet]
        public ActionResult DepartmanEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DepartmanEkle(Departman departman)
        {
            departman.Durum = true;
            _context.Departmans.Add(departman);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DepartmanSil(int id)
        {
            var cari = _context.Departmans.Find(id);
            cari.Durum = false;
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DepartmanGetir(int id)
        {
            return View(_context.Departmans.Find(id));
        }

        public ActionResult DepartmanGuncelle(Departman departman)
        {
            Departman dpr=_context.Departmans.Find(departman.DepartmanId);
            dpr.DepartmanAd = departman.DepartmanAd;
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult DepartmanDetay(int id)
        {
            var personels = _context.Personels.Where(m => m.PersonelId == id).ToList();
            var departman = _context.Departmans.Where(m => m.DepartmanId == id).Select(m => m.DepartmanAd).FirstOrDefault();

            ViewBag.departmanAdi = departman;
            return View(personels);
        }

        public ActionResult DepartmanPersonelSatis(int id)
        {
            var satislar = _context.SatisHarekets.Where(m => m.PersonelId == id).ToList();

            var personel=_context.Personels.Find(id);
            ViewBag.departmanPersonel = personel.PersonelAd +" "+personel.PersonelSoyad;
            return View(satislar);
        }
    }
}

OnlineTicariOtomasyon/Views/Departman/DepartmanDetay.cshtml
@using OnlineTicariOtomasyon.Models.Siniflar
@model List<Personel>

@{
    ViewBag.Title = "DepartmanDetay";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h4>Departman Detay</h4>
<br />

<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">@ViewBag.departmanAdi</li>
</ol>

<table class="table table-hover">
    <tr>
        <th>Personel</th>
        <th>Personel Satışlar</th>
    </tr>

    @foreach (Personel personel in Model)
    {
        <tr>
            <td>@personel.PersonelAd @personel.PersonelSoyad</td>
            <td><a href="/Departman/DepartmanPersonelSatis/@personel.PersonelId" class="btn btn-default" style="background-color:darkorange">Satışlar</a></td>
        </tr>
    }



</table>

OnlineTicariOtomasyon/Views/Departman/DepartmanEkle.cshtml
@using OnlineTicariOtomasyon.Models.Siniflar
@model Departman

@{
    ViewBag.Title = "DepartmanEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h4>Departman Ekle</h4>
<br />

@using (Html.BeginForm())
{
    @Html.LabelFor(m => m.DepartmanAd)
    @Html.TextBoxFor(m => m.DepartmanAd, new { @class = "form-control" })
    <br />

    <button class="btn btn-primary">Kaydet</button>
}

OnlineTicariOtomasyon/Views/Departman/DepartmanGetir.cshtml
@model  OnlineTicariOtomasyon.Models.Siniflar.Departman

@{
    ViewBag.Title = "DepartmanGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h4>Departman Güncelleme</h4>
<br />

@using (Html.BeginForm("DepartmanGuncelle", "Departman", FormMethod.Post))
{
    <div class="form-group">

        @Html.LabelFor(m => m.DepartmanAd)
        @Html.TextBoxFor(m => m.DepartmanAd, new { @class = "form-control" })
        @Html.HiddenFor(m => m.DepartmanId)
    </div>
    <button class="btn btn-warning">Güncelle</button>

}

OnlineTicariOtomasyon/Views/Departman/DepartmanPersonelSatis.cshtml
@using OnlineTicariOtomasyon.Models.Siniflar
@model  List<SatisHareket>

@{
    ViewBag.Title = "DepartmanPersonelSatis";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h4>Personel Satış</h4>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">@ViewBag.departmanPersonel</li>
</ol>

<table class="table table-condensed">
    <tr>
        <th>Ürün</th>
        <th>Cari</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
        <th>Yazdır</th>
    </tr>

    @foreach (SatisHareket satis in Model)
    {
        <tr>
            <td>@satis.Urun.UrunAdi</td>
            <td>@satis.Cari.CariAd @satis.Cari.CariSoyad</td>
            <td>@satis.Fiyat ₺</td>
            <td>@satis.Adet</td>
            <td>@satis.ToplamTutar</td>
            <td>@satis.Tarih</td>
            <td><a href="#" class="btn btn-default" style="background-color:ButtonShadow">Yazdır</a></td>
        </tr>  
    }
</table>

OnlineTicariOtomasyon/Views/Departman/Index.cshtml
@using OnlineTicariOtomasyon.Models.Siniflar

@model List<Departman>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<table class="table table-bordered" style="margin-top:20px">
    <tr>
        <th>ID</th>
        <th>Departman Adı</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>


    @foreach (Departman departman in Model)
    {
        <tr>
            <td>@departman.DepartmanId</td>
            <td>@departman.DepartmanAd</td>
            <td><a href="/Departman/DepartmanSil/@departman.DepartmanId" class="btn btn-danger">Sil</a></td>
            <td><a href="/Departman/DepartmanGetir/@departman.DepartmanId" class="btn btn-warning">Güncelle</a></td>
            <td><a href="/Departman/DepartmanDetay/@departman.DepartmanId" class="btn btn-default" style="background-color:lightcoral;color:white">Detaylar</a></td>
        </tr>
    }
</table>

<a href="/Departman/DepartmanEkle" class="btn btn-info">Departman Ekle</a>