OnlineTicariOtomasyon/Controllers/SatisController.cs
using OnlineTicariOtomasyon.Models.Siniflar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineTicariOtomasyon.Controllers
{
    public class SatisController : Controller
    {
        Context _context = new Context();
        public ActionResult Index()
        {
            
            return View(_context.SatisHarekets.ToList());
        }

        [HttpGet]
        public ActionResult YeniSatis()
        {
            List<SelectListItem> urunler = (from urun in _context.Uruns.ToList()
                                            select new SelectListItem
                                            {
                                                Text = urun.UrunAdi,
                                                Value = urun.UrunId.ToString(),
                                            }).ToList();

            List<SelectListItem> cariler = (from cari in _context.Caris.ToList()
                                            select new SelectListItem
                                            {
                                                Text = cari.CariAd+"" +cari.CariSoyad,
                                                Value = cari.CariId.ToString(),
                                            }).ToList();

            List<SelectListItem> personeller = (from personel in _context.Personels.ToList()
                                            select new SelectListItem
                                            {
                                                Text = personel.PersonelAd+ "" +personel.PersonelSoyad,
                                                Value = personel.PersonelId.ToString(),
                                            }).ToList();
            ViewBag.products = urunler;
            ViewBag.companies = cariler;
            ViewBag.personels = personeller;

            return View();
        }
        [HttpPost]
        public ActionResult YeniSatis(SatisHareket satis)
        {
            satis.Tarih = DateTime.Parse(DateTime.Now.ToShortDateString());
            _context.SatisHarekets.Add(satis);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SatisGetir(int id)
        {
            List<SelectListItem> urunler = (from urun in _context.Uruns.ToList()
                                            select new SelectListItem
                                            {
                                                Text = urun.UrunAdi,
                                                Value = urun.UrunId.ToString(),
                                            }).ToList();

            List<SelectListItem> cariler = (from cari in _context.Caris.ToList()
                                            select new SelectListItem
                                            {
                                                Text = cari.CariAd + " " + cari.CariSoyad,
                                                Value = cari.CariId.ToString(),
                                            }).ToList();

            List<SelectListItem> personeller = (from personel in _context.Personels.ToList()
                                                select new SelectListItem
                                                {
                                                    Text = personel.PersonelAd + " " + personel.PersonelSoyad,
                                                    Value = personel.PersonelId.ToString(),
                                                }).ToList();
            ViewBag.products = urunler;
            ViewBag.companies = cariler;
            ViewBag.personels = personeller;

            return View(_context.SatisHarekets.Find(id));
        }

        public ActionResult SatisGuncelle(SatisHareket satisHareket)
        {
            var satisFind=_context.SatisHarekets.Find(satisHareket.SatisId);

            satisFind.CariId = satisHareket.CariId;
            satisFind.Adet = satisHareket.Adet;
            satisFind.Fiyat = satisHareket.Fiyat;
            satisFind.PersonelId = satisHareket.PersonelId;
            satisFind.Tarih = satisHareket.Tarih;
            satisFind.ToplamTutar = satisHareket.ToplamTutar;
            satisFind.UrunId = satisHareket.UrunId;

            _context.SaveChanges();


            return RedirectToAction("Index");
        }

        public ActionResult SatisDetay(int id)
        {
            var satislar = _context.SatisHarekets.Where(m => m.SatisId == id).ToList();
            return View(satislar);
        }
    }
}

OnlineTicariOtomasyon/Views/Satis/Index.cshtml
@using OnlineTicariOtomasyon.Models.Siniflar
@model  List<SatisHareket>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<table id="tbl1" class="table table-bordered" style="margin-top:20px">
    <thead>
        <tr>
            <th>ID</th>
            <th>Ürün</th>
            <th>Cari </th>
            <th>Personel</th>
            <th>Adet</th>
            <th>Fiyat</th>
            <th>Toplam</th>
            <th>Tarih</th>
            <th>Güncelle</th>
            <th>Detaylar</th>
        </tr>
    </thead>

    @foreach (SatisHareket satislar in Model)
    {
        <tr>
            <td>@satislar.SatisId</td>
            <td>@satislar.Urun.UrunAdi</td>
            <td>@satislar.Cari.CariAd @satislar.Cari.CariSoyad</td>
            <td>@satislar.Personel.PersonelAd @satislar.Personel.PersonelSoyad</td>
            <td>@satislar.Adet</td>
            <td>@satislar.Fiyat</td>
            <td>@satislar.ToplamTutar</td>
            <td>@satislar.Tarih</td>
            <td><a href="/Satis/SatisGetir/@satislar.SatisId" class="btn btn-warning">Güncelle</a></td>
            <td><a href="/Satis/SatisDetay/@satislar.SatisId" class="btn btn-default" style="background-color:lightcoral;color:white">Detaylar</a></td>
        </tr>
    }
</table>

<a href="/Satis/YeniSatis" class="btn btn-info">Yeni Satış Yap</a>

@*<link href="~/Content/bootstrap.css" rel="stylesheet" />*@

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>


<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>

<script>
    $('#tbl1').dataTable({});
</script>

OnlineTicariOtomasyon/Views/Satis/SatisDetay.cshtml
@using OnlineTicariOtomasyon.Models.Siniflar
@model  List<SatisHareket>



@{
    ViewBag.Title = "SatisDetay";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h4>Satış Detayı</h4>
<br />

<table class="table table-condensed">
    <tr>
        <th>Satış Id</th>
        <th>Ürün</th>
        <th>Cari</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
    </tr>

    @foreach (SatisHareket satis in Model)
    {
        <tr>
            <td>@satis.SatisId</td>
            <td>@satis.Urun.UrunAdi</td>
            <td>@satis.Cari.CariAd @satis.Cari.CariSoyad</td>
            <td>@satis.Fiyat</td>
            <td>@satis.Adet</td>
            <td>@satis.ToplamTutar</td>
            <td>@satis.Tarih</td>
           
        </tr>

    }
</table>

<button class="btn btn-default" style="background-color:dodgerblue">Yazdır</button>

OnlineTicariOtomasyon/Views/Satis/SatisGetir.cshtml
@model OnlineTicariOtomasyon.Models.Siniflar.SatisHareket

@{
    ViewBag.Title = "SatisGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h4>Satış Güncelleme</h4>
<br />

@using (Html.BeginForm("SatisGuncelle", "Satis", FormMethod.Post))
{
    @Html.HiddenFor(m => m.SatisId)
    @Html.LabelFor(m => m.Urun)
    @Html.DropDownListFor(m => m.UrunId, (List<SelectListItem>)ViewBag.products, new { @class = "form-control" })
    <br />
    @Html.Label("Cari")
    @Html.DropDownListFor(m => m.CariId, (List<SelectListItem>)ViewBag.companies, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.PersonelId)
    @Html.DropDownListFor(m => m.PersonelId, (List<SelectListItem>)ViewBag.personels, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.Adet)
    @Html.TextBoxFor(m => m.Adet, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.Fiyat)
    @Html.TextBoxFor(m => m.Fiyat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.ToplamTutar)
    @Html.TextBoxFor(m => m.ToplamTutar, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.Tarih)
    @Html.TextBoxFor(m => m.Tarih, new { @class = "form-control" })
    <br />

    <button class="btn btn-primary">Kaydet</button>
}

OnlineTicariOtomasyon/Views/Satis/YeniSatis.cshtml
@model OnlineTicariOtomasyon.Models.Siniflar.SatisHareket

@{
    ViewBag.Title = "YeniSatis";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h4>Yeni Satış</h4>
<br />

@using (Html.BeginForm())
{
    @Html.LabelFor(m => m.Urun)
    @Html.DropDownListFor(m => m.UrunId,(List<SelectListItem>)ViewBag.products,new { @class = "form-control" })
    <br />
    @Html.Label("Cari")
    @Html.DropDownListFor(m => m.CariId,(List<SelectListItem>)ViewBag.companies,new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.PersonelId)
    @Html.DropDownListFor(m => m.PersonelId,(List<SelectListItem>)ViewBag.personels,new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.Adet)
    @Html.TextBoxFor(m => m.Adet, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.Fiyat)
    @Html.TextBoxFor(m => m.Fiyat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.ToplamTutar)
    @Html.TextBoxFor(m => m.ToplamTutar, new { @class = "form-control" })
    <br />

    <button class="btn btn-primary">Kaydet</button>
}