OnlineTicariOtomasyon/Controllers/IstatistikController.cs
using OnlineTicariOtomasyon.Models.Siniflar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineTicariOtomasyon.Controllers
{
    public class IstatistikController : Controller
    {
        Context _context = new Context();
        public ActionResult Index()
        {
            var dgr1=_context.Caris.Count().ToString();
            ViewBag.cari = dgr1;

            var dgr2 = _context.Uruns.Count().ToString();
            ViewBag.urun = dgr2;

            var dgr3 = _context.Personels.Count().ToString();
            ViewBag.personel = dgr3;

            var dgr4 = _context.Kategories.Count().ToString();
            ViewBag.kategori = dgr4;

            var dgr5 = _context.Uruns.Sum(m => m.Stok).ToString();
            ViewBag.stok= dgr5;

            var dgr6 = _context.Uruns.Count(m => m.Stok < 20).ToString();
            ViewBag.kritik= dgr6;

            var dgr7 = (from x in _context.Uruns select x.Marka).Distinct().Count().ToString();
            ViewBag.marka = dgr7;

            var dgr8 = (from x in _context.Uruns orderby x.SatisFiyat descending select x.UrunAdi).FirstOrDefault();
            ViewBag.maxUrun = dgr8;

            var dgr9 = (from x in _context.Uruns orderby x.SatisFiyat ascending select x.UrunAdi).FirstOrDefault();
            ViewBag.minUrun= dgr9;

            var dgr10 = _context.Uruns.Count(m => m.UrunAdi=="Buzdolabı").ToString();
            ViewBag.buzdolabiSayisi = dgr10;

            var dgr11 = _context.Uruns.Count(m => m.UrunAdi == "Laptop").ToString();
            ViewBag.laptopSayisi = dgr11;

            var dgr12 = _context.Uruns.GroupBy(m => m.Marka).OrderByDescending(z => z.Count()).Select(y => y.Key).FirstOrDefault();
            ViewBag.maxMarka = dgr12;

            var dgr13 = (_context.Uruns.Where(u => u.UrunId == (_context.SatisHarekets.GroupBy(x => x.UrunId).OrderByDescending(y => y.Count()).Select(m => m.Key).FirstOrDefault())).Select(t => t.UrunAdi).FirstOrDefault());
            ViewBag.encokSatilan = dgr13;

            var dgr14 = _context.SatisHarekets.Sum(m => m.ToplamTutar).ToString();
            ViewBag.toplamSatis = dgr14;

            var dgr15 = _context.SatisHarekets.Count(m => m.Tarih==DateTime.Today).ToString();
            ViewBag.satisBugun= dgr15;

            var dgr16 = _context.SatisHarekets.Where(x => x.Tarih == DateTime.Today).Sum(y =>(decimal?) y.ToplamTutar).ToString();
            ViewBag.satisBugunToplam = dgr16;

            return View();
        }

        public ActionResult ProgressTable()
        {
            var sorgu = from x in _context.Caris
                        group x by x.CariSehir into g
                        select new SinifGrup
                        {
                            Sehir = g.Key,
                            Sayi = g.Count()
                        };

            return View(sorgu.ToList());
        }

        public PartialViewResult Partial1()
        {
            var sorgu2 = from x in _context.Personels
                         group x by x.Departman.DepartmanAd into g
                         select new SinifGrup2
                         {
                             Departman = g.Key,
                             Sayi = g.Count()
                         };
            return PartialView(sorgu2.ToList());
        }

        public PartialViewResult Partial2()
        {
            var sorgu = _context.Caris.ToList();
            return PartialView(sorgu);
        }

        public PartialViewResult Partial3()
        {
            var sorgu = _context.Uruns.ToList();
            return PartialView(sorgu);
        }

        public PartialViewResult Partial4()
        {

            var sorgu = from x in _context.Uruns
                         group x by x.Marka into g
                         select new SinifGrup3
                         {
                             Marka = g.Key,
                             sayi = g.Count()
                         };
            return PartialView(sorgu.ToList());
        }
    }
}

OnlineTicariOtomasyon/Views/Istatistik/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>

    <!-- Custom Theme files -->
    <link href="~/web2/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- Custom Theme files -->
    <script src="~/web2/js/jquery.min.js"></script>
    <link rel="stylesheet" href="~/web2/css/font-awesome.css">
    <!-- Custom Theme files -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Metro Panel Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--webfont-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <script src="js/zingchart.min.js"></script>
    <script src="js/zingchart.jquery.js"></script>
    <script src="js/jquery.easydropdown.js"></script>
    <script src="js/jquery.nicescroll.js"></script>

    <link href="css/jqvmap.css" media="screen" rel="stylesheet" type="text/css" />


    <script src="~/web2/js/easyResponsiveTabs.js" type="text/javascript"></script>

    <link href="~/web2/css/nav.css" rel="stylesheet" type="text/css" media="all" />
    <script src="~/web2/js/main.js"></script> <!-- Resource jQuery -->
    <!-- chart -->
    <script src="~/web2/js/Chart1.js"></script>
    <!-- //chart -->
</head>
<body>
    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#1abc9c">
                <div class="icon-text">
                    <h3>@ViewBag.cari</h3>
                    <p>Toplam Cari</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#2ecc71">

                <div class="icon-text">
                    <h3>@ViewBag.urun</h3>
                    <p>Ürün Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#3498db">

                <div class="icon-text">
                    <h3>@ViewBag.personel</h3>
                    <p>Personel Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#9b59b6">

                <div class="icon-text">
                    <h3>@ViewBag.kategori</h3>
                    <p>Kategori Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="clearfix"></div>

    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#16a085">
                <div class="icon-text">
                    <h3>@ViewBag.stok</h3>
                    <p>Toplam Stok</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#27ae60">

                <div class="icon-text">
                    <h3>@ViewBag.marka</h3>
                    <p>Marka Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#2980b9">

                <div class="icon-text">
                    <h3>@ViewBag.kritik</h3>
                    <p>Kritik Seviye</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#8e44ad">

                <div class="icon-text">
                    <h3>@ViewBag.maxUrun</h3>
                    <p>Max Fiyatlı Ürün</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>


    <div class="clearfix"></div>

    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#f1c40f">
                <div class="icon-text">
                    <h3>@ViewBag.minUrun</h3>
                    <p>Min Fiyatlı Ürün</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#e67e22">

                <div class="icon-text">
                    <h3>@ViewBag.maxMarka</h3>
                    <p>Max Marka</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#e74c3c">

                <div class="icon-text">
                    <h3>@ViewBag.buzdolabiSayisi</h3>
                    <p>Buzdolabı Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#95a5a6">

                <div class="icon-text">
                    <h3>@ViewBag.laptopSayisi</h3>
                    <p>Laptop Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <div class="clearfix"></div>

    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#f39c12">
                <div class="icon-text">
                    <h3>@ViewBag.encokSatilan</h3>
                    <p>En Çok Satan</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#d35400">

                <div class="icon-text">
                    <h3>@ViewBag.toplamSatis</h3>
                    <p>Kasadaki Tutar</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#c0392b">

                <div class="icon-text">
                    <h3>@ViewBag.satisBugun</h3>
                    <p>Bugünkü Satşlar</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#7f8c8d">

                <div class="icon-text">
                    <h3>@ViewBag.satisBugunToplam</h3>
                    <p>Bugünkü Kasa</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</body>
</html>

OnlineTicariOtomasyon/Views/Istatistik/Partial1.cshtml
@model  IEnumerable<OnlineTicariOtomasyon.Models.Siniflar.SinifGrup2>

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Departman Personel Sayıları</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
        <table class="table table-sm">
            <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Departman</th>
                    <th>Progress Bar</th>
                    <th style="width: 40px">Kişi Sayısı</th>
                </tr>
            </thead>
            <tbody>
                @{ int siraNo = 0;}
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@{siraNo++;}@siraNo</td>
                        <td>@item.Departman</td>
                        <td>
                            @if (item.Sayi == 1)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                </div>
                            }
                            @if (item.Sayi == 2)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar bg-warning" style="width: 55%"></div>
                                </div>
                            }
                            @if (item.Sayi == 3)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar bg-success" style="width: 55%"></div>
                                </div>
                            }
                        </td>
                        <td>
                            @if (item.Sayi == 1)
                            {<span class="badge bg-danger">@item.Sayi</span>}
                            @if (item.Sayi == 2)
                            {<span class="badge bg-success">@item.Sayi</span>}
                            @if (item.Sayi == 3)
                            {<span class="badge bg-gradient-fuchsia">@item.Sayi</span>}
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>

OnlineTicariOtomasyon/Views/Istatistik/Partial2.cshtml
@using OnlineTicariOtomasyon.Models.Siniflar

@model  List<Cari>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Cariler Tablosu</h3>

                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Ad</th>
                            <th>Soyad</th>
                            <th>Şehir</th>
                            <th>Mail</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>@item.CariId</td>
                            <td>@item.CariAd</td>
                            <td>@item.CariSoyad</td>
                            <td>@item.CariSehir</td>
                            <td>@item.CariMail</td>
                          
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</div>

OnlineTicariOtomasyon/Views/Istatistik/Partial3.cshtml
@using OnlineTicariOtomasyon.Models.Siniflar

@model  List<Urun>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Ürün Bilgi Tablosu</h3>

                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0" style="height: 300px;">
                <table class="table table-head-fixed text-nowrap">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Ürün Adı</th>
                            <th>Marka</th>
                            <th>Stok</th>
                            <th>Alış Fİyat</th>
                            <th>Satış Fİyat</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.UrunId</td>
                                <td>@item.UrunAdi</td>
                                <td>@item.Marka</td>
                                <td>@item.Stok</td>
                                <td>@item.AlisFiyat ₺</td>
                                <td>@item.SatisFiyat ₺</td>
                               
                            </tr>
                        }
                        </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</div>

OnlineTicariOtomasyon/Views/Istatistik/Partial4.cshtml
@using OnlineTicariOtomasyon.Models.Siniflar

@model  List<SinifGrup3>

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Ürün Marka Tablosu</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Marka</th>
                    <th>Progress Bar</th>
                    <th style="width: 40px">Toplam</th>
                </tr>
            </thead>
            <tbody>
                @{ int siraNo = 0;}
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@{siraNo++;}@siraNo</td>
                        <td>@item.Marka</td>
                        <td>
                            @if (item.sayi>= 1 && item.sayi<=3) 
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                </div>
                            }
                            @if (item.sayi >= 4 && item.sayi <= 6)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar bg-warning" style="width: 55%"></div>
                                </div>
                            }
                            @if (item.sayi >= 7)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar bg-success" style="width: 55%"></div>
                                </div>
                            }
                        </td>
                        <td>
                            @if (item.sayi >= 1 && item.sayi <= 3)
                            {<span class="badge bg-danger">@item.sayi</span>}
                            @if (item.sayi >= 4 && item.sayi <= 6)
                            {<span class="badge bg-success">@item.sayi</span>}
                            @if (item.sayi >= 7)
                            {<span class="badge bg-gradient-fuchsia">@item.sayi</span>}
                        </td>
                    </tr>
                }


            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>

OnlineTicariOtomasyon/Views/Istatistik/ProgressTable.cshtml
@model  IEnumerable<OnlineTicariOtomasyon.Models.Siniflar.SinifGrup>

@{
    ViewBag.Title = "ProgressTable";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@*<h4>Süreç Tablosu</h4>*@
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Süreç Tablosu</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Navbar -->
  
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h4>Hızlı Bakış Tabloları</h4>
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title">Kategori Tablosu</h3>
                                </div>
                                <!-- /.card-header -->
                                <div class="card-body">
                                    <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th style="width: 10px">#</th>
                                                <th>Kategori Adı</th>
                                                <th>Progress Bar</th>
                                                <th style="width: 40px">Oran</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>1.</td>
                                                <td>Beyaz Eşya</td>
                                                <td>
                                                    <div class="progress progress-xs">
                                                        <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                                    </div>
                                                </td>
                                                <td><span class="badge bg-danger">55%</span></td>
                                            </tr>
                                            <tr>
                                                <td>2.</td>
                                                <td>Telefon</td>
                                                <td>
                                                    <div class="progress progress-xs">
                                                        <div class="progress-bar bg-warning" style="width: 70%"></div>
                                                    </div>
                                                </td>
                                                <td><span class="badge bg-warning">70%</span></td>
                                            </tr>
                                            <tr>
                                                <td>3.</td>
                                                <td>Küçük Ev Aleti</td>
                                                <td>
                                                    <div class="progress progress-xs progress-striped active">
                                                        <div class="progress-bar bg-primary" style="width: 30%"></div>
                                                    </div>
                                                </td>
                                                <td><span class="badge bg-primary">30%</span></td>
                                            </tr>
                                            <tr>
                                                <td>4.</td>
                                                <td>Bilgisayar</td>
                                                <td>
                                                    <div class="progress progress-xs progress-striped active">
                                                        <div class="progress-bar bg-success" style="width: 90%"></div>
                                                    </div>
                                                </td>
                                                <td><span class="badge bg-success">90%</span></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <!-- /.card-body -->

                            </div>
                            <!-- /.card -->

                            @Html.Action("Partial1", "Istatistik")

                            <!-- /.card -->
                        </div>
                        <!-- /.col -->
                        <div class="col-md-6">
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title">Müşteri Şehir Tablosu</h3>

                                    <div class="card-tools">

                                    </div>
                                </div>
                                <!-- /.card-header -->
                                <div class="card-body p-0">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th style="width: 10px">#</th>
                                                <th>Şehir</th>
                                                <th>Progress Bar</th>
                                                <th style="width: 40px">Adet</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @{ int siraNo = 0;}
                                            @foreach (var item in Model)
                                            {
                                                <tr>
                                                    <td>@{siraNo++;}@siraNo</td>
                                                    <td>@item.Sehir</td>
                                                    <td>
                                                        @if (item.Sayi == 1)
                                                        {
                                                            <div class="progress progress-xs">
                                                                <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                                            </div>
                                                        }
                                                        @if (item.Sayi == 2)
                                                        {
                                                            <div class="progress progress-xs">
                                                                <div class="progress-bar bg-warning" style="width: 55%"></div>
                                                            </div>
                                                        }
                                                        @if (item.Sayi == 3)
                                                        {
                                                            <div class="progress progress-xs">
                                                                <div class="progress-bar bg-success" style="width: 55%"></div>
                                                            </div>
                                                        }
                                                    </td>
                                                    <td>
                                                        @if (item.Sayi == 1)
                                                        {<span class="badge bg-danger">@item.Sayi</span>}
                                                        @if (item.Sayi == 2)
                                                        {<span class="badge bg-success">@item.Sayi</span>}
                                                        @if (item.Sayi == 3)
                                                        {<span class="badge bg-gradient-fuchsia">@item.Sayi</span>}
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                                <!-- /.card-body -->
                            </div>
                            <!-- /.card -->

                            @Html.Action("Partial4","Istatistik")
                            <!-- /.card -->
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                    @Html.Action("Partial2", "Istatistik")
                    <!-- /.row -->
                    @Html.Action("Partial3", "Istatistik")
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
  
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="../../dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="../../dist/js/demo.js"></script>
</body>
</html>